### ISSUE TITLE
Migrate to Firestore Security Rules

### ISSUE THREAD

**Issue by rishabnayak** [Bostonhacks/cacioepepe#102]
Migrate to Firestore Security Rules, and then enable Offline Persistence

**Comment by vitorvicente** [comment]
Splitting the work of migrating to security rules between Firestore and Storage, starting with Firestore the following needs to be done:

Firebase Firestore:
- Make Security Rules
  - [ ] Users
  - [ ] Teams
  - [ ] Applications
  - Admin
    - [ ] FAQs
    - [ ] devpostDoc
    - [ ] prizesDoc
    - [ ] regDeadline
    - [ ] schedules
    - [ ] slackInfo
    - [ ] tracksDoc
    - [ ] wifiDetails
- Migrate Codebase outside of functions
  - [ ] createNewUser
  - [ ] getUserData
  - [ ] createNewVolunteer
  - [ ] submitVolunteerApplication
  - [ ] createNewSponsor
  - [ ] createNewMentor
  - [ ] submitMentorApplication
  - [ ] createApplication
  - [ ] saveApplication
  - [ ] loadApplication
  - [ ] submitApplication
  - [ ] checkinApplicant
  - [ ] acceptApplicant
  - [ ] massRejectEmail
  - [ ] massWaitlistEmail
  - [ ] rejectApplicant
  - [ ] retrieveAllApplications
  - [ ] waitlistApplicant
  - [ ] createDeadline
  - [ ] readDeadline
  - [ ] createDevpost
  - [ ] createWifiDetails
  - [ ] deleteDevpost
  - [ ] deleteWifi
  - [ ] readAllDevpost
  - [ ] readAllPrizes
  - [ ] readFAQ
  - [ ] updateDeadline
  - [ ] updateDevpost
  - [ ] acceptMentor
  - [ ] acceptVolunteer
  - [ ] massAcceptMentor
  - [ ] massAcceptVolunteer
  - [ ] massRejectMentor
  - [ ] massRejectVolunteer
  - [ ] rejectMentor
  - [ ] rejectVolunteer
  - [ ] retrieveAllMentors
  - [ ] retrieveAllVolunteers
  - [ ] createTrack
  - [ ] createWifiDetails
  - [ ] deleteFAQ
  - [ ] deletePrize
  - [ ] deleteSchedule
  - [ ] deleteTrack
  - [ ] readFAQs
  - [ ] readPrizes
  - [ ] readSchedules
  - [ ] readTracks
  - [ ] readWifiDetails
  - [ ] updateEvent
  - [ ] updateFAQ
  - [ ] updatePrize
  - [ ] updateTracks
  - [ ] updateWifiDetails
  - [ ] uploadSlackInfo

**Comment by rishabnayak** [comment]
Docs on [Offline Persistence](https://firebase.google.com/docs/firestore/manage-data/enable-offline)
