### ISSUE TITLE
Hacker View: QR Codes

### ISSUE THREAD

**Issue by xav-ie** [Bostonhacks/cacioepepe#36]
QR codes are important so that hackers may get food, check-in, and do other activities throughout the hackathon. We are putting QR codes into the hacker view. We must:
- Generate QR codes once user has confirmed their acceptance. This QR code should produce their UID from firebase when scanned.
- Store this QR code in firebase.
- Sign the QR code and find a way to do it so that we can do it through a server function, not with an executable that Apple provides. Currently, we can only run the executable on a Mac.

**Comment by rishabnayak** [comment]
display in hacker dash?

**Comment by rishabnayak** [comment]
@xav-ie is this complete?
