### ISSUE TITLE
Admin View: Site Customization

### ISSUE THREAD

**Issue by jfeng5529** [Bostonhacks/cacioepepe#42]
Ability to edit application submission deadline, schedule, tracks, workshops, prizes, FAQ, wifi details, slack channel name, devpost submission link.

**Comment by jinyoungbang** [comment]
@ychai23 Registration/Acceptance Update Front-end Component
@jfeng5529 @asifrahman479 @jy-clairechoi Schedule Front-end component
@asifrahman479 @jy-clairechoi Firebase Functions to to do CRUD on tracks, workshops, prizes, FAQ, wifi details, slack channel name, devpost submission link.

**Comment by rishabnayak** [comment]
@jinyoungbang how's this looking?

**Comment by jinyoungbang** [comment]
@rishabnayak totally lost track of this but I remember Claire and Asif finished the firebase functions!

**Comment by rishabnayak** [comment]
okay that's alright it'd be great if we can have the front end built out for this please
